# Generated by Django 5.2 on 2025-06-19 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_favorited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorited_by',
        ),
    ]
