# Generated by Django 5.2 on 2025-06-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('processing', 'Собирается'), ('shipped', 'В пути'), ('delivered', 'Доставлен')], default='pending', max_length=20),
        ),
    ]
