# Generated by Django 5.2 on 2025-06-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_city_order_country_order_ip_address_order_isp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает потверждения'), ('processing', 'Собирается'), ('shipped', 'В пути'), ('delivered', 'Доставлен')], default='pending', max_length=20),
        ),
    ]
